/**
 * Google Fonts directory access — reads the bundled snapshot generated by
 * `scripts/build-google-fonts.ts`.
 *
 * The snapshot is a flat JSON file (~270 KiB) shipped with the build; refresh
 * by re-running the script. Nothing in the editor reaches out to Google's CDN
 * for the directory list — preview previews of individual families do (see
 * `core/fonts/preview.ts`), but they're transient and never end up in the
 * published output.
 */

import directory from './google-fonts.json' with { type: 'json' }
import type { GoogleFontDirectory, GoogleFontFamily } from './types'

const cast = directory as GoogleFontDirectory

export function listGoogleFonts(): GoogleFontFamily[] {
  return cast.families
}

export function findGoogleFont(family: string): GoogleFontFamily | undefined {
  if (!family) return undefined
  return cast.families.find((f) => f.family === family)
}
