/**
 * Files Data Layer — TypeBox schemas and derived types.
 *
 * Schemas are the source of truth. Types are derived via `Static<typeof T>`.
 *
 * Architecture source: Contribution #595 §1.2
 *
 * SiteFile is stored as a flat array in site.files (parallel to
 * site.pages). The same flat-map reasoning drives Page.nodes
 * (Decision #309 / Constraint #215).
 *
 * Path invariants are enforced at every write boundary by isSafePath()
 * in pathValidation.ts.
 */

import { Type, type Static } from '@sinclair/typebox'

// ---------------------------------------------------------------------------
// SiteFileType
// ---------------------------------------------------------------------------

const SiteFileTypeSchema = Type.Union([
  Type.Literal('component'), // src/components/*.tsx — user-authored React components
  Type.Literal('script'),    // src/scripts/*.ts, src/utils/*.ts, src/hooks/*.ts
  Type.Literal('style'),     // src/styles/*.css — global CSS
  Type.Literal('asset'),     // public/* — images, fonts, etc. (binary)
  Type.Literal('config'),    // package.json, tsconfig.json, vite.config.ts, .env, etc.
  Type.Literal('doc'),       // README.md, CHANGELOG.md — markdown docs
])

export type SiteFileType = Static<typeof SiteFileTypeSchema>

// ---------------------------------------------------------------------------
// SiteFile
// ---------------------------------------------------------------------------

const SiteFileBlobSchema = Type.Object({
  mimeType: Type.String(),
  base64: Type.String(),
})


export const SiteFileSchema = Type.Object({
  /** Unique ID — generated with nanoid() (NOT path; path is mutable on rename) */
  id: Type.String(),

  /**
   * POSIX-style path relative to site root.
   * Examples: "src/components/MyButton.tsx", "public/logo.png", "package.json"
   * Validated by isSafePath() at every write boundary.
   * Must be unique within site.files[].
   */
  path: Type.String(),

  type: SiteFileTypeSchema,

  /**
   * Text content for component/script/style/config/doc (UTF-8).
   * For 'asset' files this is undefined; binary content lives in `blob`.
   */
  content: Type.Optional(Type.String()),

  /**
   * Binary payload for asset files — base64-encoded mime + bytes.
   * Stored as a plain object inside SiteDocument so structuredClone/Immer
   * equality keeps working; a real Blob would defeat that.
   * Always undefined for non-asset file types.
   *
   * Lenient: a malformed blob silently becomes undefined so the file is still
   * included. Mirrors validateSiteFile() which keeps the file with blob:undefined
   * when mimeType/base64 are missing or wrong type.
   */
  blob: Type.Optional(SiteFileBlobSchema),

  /**
   * When true, the file was auto-generated by the scaffold (e.g. package.json,
   * vite.config.ts, src/main.tsx). Generated files are read-only in the UI
   * until the user "ejects" them (sets ejected: true).
   *
   * Generated files are hidden from normal authoring UI until ejected.
   */
  generated: Type.Optional(Type.Boolean()),

  /**
   * When true, the user has edited a previously-generated file.
   * Only meaningful when `generated === true`.
   */
  ejected: Type.Optional(Type.Boolean()),

  /** Falls back to Date.now() for missing or non-numeric values */
  createdAt: Type.Number(),
  /** Falls back to Date.now() for missing or non-numeric values */
  updatedAt: Type.Number(),
})

export type SiteFile = Static<typeof SiteFileSchema>
